---
version: '3'

services:
  vector_vm:
    image: pycontribs/ubuntu
    container_name: vector-01
    restart: unless-stopped
    entrypoint: "sleep infinity"
    ports:
      - "8383:8383"
      - "8686:8686"
    tty: true
